##
##  Makefile -- Build procedure for sample proxy_protocol Apache module
##  Autogenerated via ``apxs -n proxy_protocol -g''.
##

#   the used tools
APXS=apxs
XSLT=xsltproc

#   the default target
all: .libs/mod_proxy_protocol.so

# build the so in the current directory
.libs/mod_proxy_protocol.so: mod_proxy_protocol.c
	$(APXS) -c -Wc,-Wall mod_proxy_protocol.c

# install the so - usually needs root access
install: .libs/mod_proxy_protocol.so
	$(APXS) -i mod_proxy_protocol.la

# generate the html doc
docs: mod_proxy_protocol.html

mod_proxy_protocol.html: mod_proxy_protocol.xml mod_proxy_protocol.xml.meta
	$(XSLT) -o $@ $<

# generate packages
dpkg:
	debuild --no-tgz-check -uc -us

#   cleanup
clean:
	-rm -rf mod_proxy_protocol.o mod_proxy_protocol.lo mod_proxy_protocol.slo mod_proxy_protocol.la .libs mod_proxy_protocol.html
