##
##  Makefile -- Build procedure for sample proxy_protocol Apache module
##  Autogenerated via ``apxs -n proxy_protocol -g''.
##

#   the used tools
APXS=apxs

#   the default target
all: .libs/mod_proxy_protocol.so

# build the so in the current directory
.libs/mod_proxy_protocol.so: mod_proxy_protocol.c
	$(APXS) -c mod_proxy_protocol.c

# install the so - usually needs root access
install: .libs/mod_proxy_protocol.so
	$(APXS) -i mod_proxy_protocol.c

#   cleanup
clean:
	-rm -rf mod_proxy_protocol.o mod_proxy_protocol.lo mod_proxy_protocol.slo mod_proxy_protocol.la .libs
